Added OurTextArea for issue 64
vnLab-Lodz/PubLab pull request #107
Opened 2021-11-09 16:14 UTC by aleksander-lemiesz

## Description

Added OurTextArea component

## Preview

![obraz](https://user-images.githubusercontent.com/53061709/140961483-36443660-6af6-4c22-9450-ee69d4aa402c.png)

## Linked issues

closes #64

2021-11-10 10:38 UTC, kmaciejewska commented
I will just add, before too much work is performed that this component can be merged with #63 as it will differ by just one prop - multiline. Also, as we discussed the palette colors have to be referenced directly here  (e.g theme.palette.lightRed.main) and mui.d.ts declarations then become reduntant. 
However, that seems to be causing issues with StoryBook:
![image](https://user-images.githubusercontent.com/73823898/141098131-0b538543-422e-4b74-8b65-9914dc6a843a.png)

2021-11-10 13:42 UTC, karczewskiPiotr commented
> I will just add, before too much work is performed, that this component can be merged with #63 as it will differ by just one prop - multiline. Also, as we discussed, the palette colours have to be referenced directly here (e.g theme.palette.lightRed.main) and mui.d.ts declarations then become redundant.
> 
> However, that seems to be causing issues with StoryBook:
> 
> ![image](https://user-images.githubusercontent.com/73823898/141098131-0b538543-422e-4b74-8b65-9914dc6a843a.png)

@aleksander-lemiesz There are two ways of using the `theme` here. 

### 1. Params of `styled` function

You can use the `theme` from the params of styled function:

```tsx
const StyledTextArea = styled(TextField)(({ type, theme: { palette } }) => {
  const { lightGray, black, lightRed } = palette;
  const color = type === 'light' ? lightGray.main : black.main;

  return {
    // styles  
  }
});
```

This however implies that you then need to wrap the story in the `ThemeProvider`, which is not ideal since you have to do it for every component then.

```ts
const Template: ComponentStory<typeof OurTextArea> = (args) => (
  <ThemeProvider theme={theme}>
    <CssBaseline />
    <OurTextArea {...args} />
  </ThemeProvider>
);
```

So it can be generalised by wrapping all stories with the `ThemeProvider` with the use of [decorators](https://storybook.js.org/docs/react/writing-stories/decorators#context-for-mocking). `.storybook/preview.js` needs to be updated to the following to achieve that:

```js
import { theme } from '../src/renderer/theme';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

export const decorators = [
  (Story) => (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      {Story()}
    </ThemeProvider>
  ),
];

```

It also seems like `storybook` is using `emotion` under the hood which conflicts with the new v5 `emotion` styling (see [here](https://github.com/mui-org/material-ui/issues/24282)). This is what is responsible for the error @kmaciejewska. It can be fixed by removing `emotion` aliases from storybook webpack configuration by updating the `.storybook/main.js` with the following:

```js
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-scss',
  ],
  webpackFinal(config) {
    delete config.resolve.alias['emotion-theming'];
    delete config.resolve.alias['@emotion/styled'];
    delete config.resolve.alias['@emotion/core'];
    return config;
  },
};

```

### 2. Directly from `theme` (less advised since it removes theme switching abilities)

```tsx
import { theme } from 'wherever it is';

const StyledTextArea = styled(TextField)(({ type }) => {
  const { lightGray, black, lightRed } = theme.palette;
  const color = type === 'light' ? lightGray.main : black.main;

  return {
    // styles  
  }
});
```

2021-11-10 18:37 UTC, karczewskiPiotr commented on src/renderer/components/OurTextArea/OurTextArea.tsx
> +const OurTextArea: React.FC<Props> = (props) => (
The name `OurTextArea` gives off huge mother Russia vibes. 😅 You can just change it to `TextArea`.

2021-11-15 08:25 UTC, karczewskiPiotr requested changes
@aleksander-lemiesz the code does not build. You can follow the directions from the comment to make it work.

2021-11-15 08:25 UTC, karczewskiPiotr commented on src/renderer/components/OurTextArea/OurTextArea.tsx
> +      },
You're using `ligthGray` and `black` and `lightRead` but they do not come from anywhere. They are not defined at all.

2021-11-16 14:00 UTC, karczewskiPiotr approved these changes

2021-11-16 14:00 UTC, merged