Issue70
vnLab-Lodz/PubLab pull request #121
Opened 2021-11-18 23:16 UTC by DziobakSz

## Description

Couldn't use #65 component because it's not finished. 

## Linked issues

closes #70

## Correct PR Checklist

- [ ] I have linked an issue (use e.g. `closes #1`)
- [ ] I have assigned Reviewers
- [ ] I have assigned an Description label
- [ ] I have assigned a Milestone (if applicable)

2021-11-20 10:52 UTC, kmaciejewska requested changes
The function that fires on the Input change should probably also be passed as a prop since the parent component will most likely use the value - and right now there is no such possibility.

2021-11-20 10:53 UTC, kmaciejewska requested changes

2021-11-20 10:53 UTC, kmaciejewska commented on src/renderer/components/DirectoryPicker/DirectoryPicker.tsx
> +    setCurrentValue(event.target.value);
handleDirectoryChange in this case will just come as a prop, the same way you handled onClick. Thus, this piece of code becomes redundant

2021-11-22 22:33 UTC, kmaciejewska submitted a review, later dismissed

2021-11-25 10:07 UTC, karczewskiPiotr approved these changes

2021-11-25 10:07 UTC, merged